/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.theyarnest.views;

import com.theyarnest.controllers.ValidationUtil;
import com.theyarnest.controllers.algorithim.InsertionSort;
import com.theyarnest.controllers.algorithim.MergeSort;
import com.theyarnest.controllers.algorithim.SelectionSort;
import com.theyarnest.model.CrochetModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ekata Baral LMU ID: 23048589
 */
public class TheYarnestFrame extends javax.swing.JFrame {

    private List<CrochetModel> productList;
    private List<CrochetModel> sortedList;
    private java.awt.CardLayout cardLayout;
    private final ValidationUtil ValidationUtil;
    
    private final SelectionSort selectionSort;
    private final InsertionSort insertionSort;
    private final MergeSort mergeSort;
    
    /**
     * Creates new form theYarnestframe
     */
    public TheYarnestFrame() {
        initComponents();

        ValidationUtil = new ValidationUtil();
        selectionSort = new SelectionSort();
        insertionSort = new InsertionSort();
        mergeSort = new MergeSort();
        
        layoutInitialize();
        forProgressBar();
        dataInitialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblSignin = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblForgetPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblLoginIcon = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        pnlAdminControls = new javax.swing.JPanel();
        pnlImage = new javax.swing.JPanel();
        lblgrannyCardigan = new javax.swing.JLabel();
        lblHalfSweater = new javax.swing.JLabel();
        lblGrannySquareCardigan = new javax.swing.JLabel();
        lblCozyGreenSweater = new javax.swing.JLabel();
        pnlForBrand = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        pnlBrandMessage = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        pnlAllProducts = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        lblOurProducts = new javax.swing.JLabel();
        btnSortId = new javax.swing.JButton();
        btnSortCategory = new javax.swing.JButton();
        btnSortMostPrice = new javax.swing.JButton();
        btnSortCategoryDesc = new javax.swing.JButton();
        btnSortLeastPrice = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pnlAddProducts = new javax.swing.JPanel();
        pnlRegistrationForm = new javax.swing.JPanel();
        lblProductRegister = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtProduct = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        boxYarn = new javax.swing.JComboBox<>();
        checkRepairable = new javax.swing.JCheckBox();
        boxCategory = new javax.swing.JComboBox<>();
        spinStock = new javax.swing.JSpinner();
        btnAddProduct = new javax.swing.JButton();
        btnUpdateProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        lblIdError = new javax.swing.JLabel();
        lblProdError = new javax.swing.JLabel();
        lblPriceError = new javax.swing.JLabel();
        lblStockError = new javax.swing.JLabel();
        lblCategoryError = new javax.swing.JLabel();
        lblYarnError = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblTagline = new javax.swing.JLabel();
        pnlLoading = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        lblLogo = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        lblYarNest = new javax.swing.JLabel();
        lblCopyright = new javax.swing.JLabel();

        pnlLogin.setBackground(new java.awt.Color(82, 91, 68));
        pnlLogin.setMaximumSize(new java.awt.Dimension(900, 600));
        pnlLogin.setMinimumSize(new java.awt.Dimension(900, 600));
        pnlLogin.setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(248, 247, 244));
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 580));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 580));

        lblSignin.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        lblSignin.setForeground(new java.awt.Color(82, 91, 68));
        lblSignin.setText("Sign-In To Shop");

        lblMessage.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(82, 91, 68));
        lblMessage.setText("Please enter user-name and password!");

        lblForgetPassword.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblForgetPassword.setForeground(new java.awt.Color(82, 91, 68));
        lblForgetPassword.setText("Forget Password?");

        txtUserName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User-Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(82, 91, 68))); // NOI18N

        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(82, 91, 68))); // NOI18N

        btnLogin.setBackground(new java.awt.Color(133, 169, 143));
        btnLogin.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnLogin.setText("Log-In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSignin)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblForgetPassword)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(86, 86, 86))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblSignin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addGap(18, 18, 18)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblForgetPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        lblLoginIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theyarnest/resources/loginpanel.jpg"))); // NOI18N
        lblLoginIcon.setMaximumSize(new java.awt.Dimension(400, 570));
        lblLoginIcon.setMinimumSize(new java.awt.Dimension(400, 570));
        lblLoginIcon.setPreferredSize(new java.awt.Dimension(400, 570));

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblLoginIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(lblLoginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlMain.setBackground(new java.awt.Color(82, 91, 68));
        pnlMain.setMaximumSize(new java.awt.Dimension(900, 600));
        pnlMain.setMinimumSize(new java.awt.Dimension(900, 600));
        pnlMain.setPreferredSize(new java.awt.Dimension(900, 600));

        tabbedPane.setBackground(new java.awt.Color(248, 247, 244));

        pnlAdminControls.setBackground(new java.awt.Color(248, 247, 244));

        pnlImage.setBackground(new java.awt.Color(82, 91, 68));
        pnlImage.setMaximumSize(new java.awt.Dimension(850, 250));
        pnlImage.setMinimumSize(new java.awt.Dimension(850, 250));
        pnlImage.setPreferredSize(new java.awt.Dimension(850, 250));

        lblgrannyCardigan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theyarnest/resources/grannySweaterCardiganNew.jpg"))); // NOI18N

        lblHalfSweater.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theyarnest/resources/halfSweater.jpg"))); // NOI18N

        lblGrannySquareCardigan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theyarnest/resources/grannySquareCardigan.jpg"))); // NOI18N

        lblCozyGreenSweater.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theyarnest/resources/cosyGreenSweater.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addComponent(lblgrannyCardigan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHalfSweater, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblCozyGreenSweater, javax.swing.GroupLayout.PREFERRED_SIZE, 238, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblGrannySquareCardigan)
                .addContainerGap())
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblgrannyCardigan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCozyGreenSweater, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGrannySquareCardigan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlImageLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblHalfSweater, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlForBrand.setBackground(new java.awt.Color(133, 169, 143));
        pnlForBrand.setMaximumSize(new java.awt.Dimension(695, 139));
        pnlForBrand.setMinimumSize(new java.awt.Dimension(695, 139));
        pnlForBrand.setPreferredSize(new java.awt.Dimension(695, 139));

        lblBrand.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(248, 247, 244));
        lblBrand.setText("Our Brand");

        pnlBrandMessage.setMaximumSize(new java.awt.Dimension(595, 64));
        pnlBrandMessage.setMinimumSize(new java.awt.Dimension(595, 64));
        pnlBrandMessage.setPreferredSize(new java.awt.Dimension(595, 64));

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextPane1.setText("We source our yarn from ethical loacl businesses and are committed to creating, producing and selling ethically sourced products. Our pledge to produce long lasting and ethically sound  products are a strong commitment to our customers.");
        jTextPane1.setAutoscrolls(false);
        jTextPane1.setMaximumSize(new java.awt.Dimension(595, 64));
        jTextPane1.setMinimumSize(new java.awt.Dimension(595, 64));
        pnlBrandMessage.setViewportView(jTextPane1);

        javax.swing.GroupLayout pnlForBrandLayout = new javax.swing.GroupLayout(pnlForBrand);
        pnlForBrand.setLayout(pnlForBrandLayout);
        pnlForBrandLayout.setHorizontalGroup(
            pnlForBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlForBrandLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(pnlBrandMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(pnlForBrandLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlForBrandLayout.setVerticalGroup(
            pnlForBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForBrandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBrandMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAdminControlsLayout = new javax.swing.GroupLayout(pnlAdminControls);
        pnlAdminControls.setLayout(pnlAdminControlsLayout);
        pnlAdminControlsLayout.setHorizontalGroup(
            pnlAdminControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminControlsLayout.createSequentialGroup()
                .addGroup(pnlAdminControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminControlsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminControlsLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(pnlForBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlAdminControlsLayout.setVerticalGroup(
            pnlAdminControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminControlsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(pnlForBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        tabbedPane.addTab("Admin Controls", pnlAdminControls);

        pnlAllProducts.setBackground(new java.awt.Color(82, 91, 68));

        tblProducts.setBackground(new java.awt.Color(248, 247, 244));
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Category", "Yarn Type", "Repairable", "Description", "Price", "Stock", "Date Added"
            }
        ));
        tblProducts.setRowSelectionAllowed(false);
        tblProducts.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProducts);

        lblOurProducts.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblOurProducts.setForeground(new java.awt.Color(248, 247, 244));
        lblOurProducts.setText("Our Products");

        btnSortId.setBackground(new java.awt.Color(133, 169, 143));
        btnSortId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSortId.setForeground(new java.awt.Color(248, 247, 244));
        btnSortId.setText("Sort by Id");
        btnSortId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortIdActionPerformed(evt);
            }
        });

        btnSortCategory.setBackground(new java.awt.Color(133, 169, 143));
        btnSortCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSortCategory.setForeground(new java.awt.Color(248, 247, 244));
        btnSortCategory.setText("Sort  by Category");
        btnSortCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortCategoryActionPerformed(evt);
            }
        });

        btnSortMostPrice.setBackground(new java.awt.Color(133, 169, 143));
        btnSortMostPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSortMostPrice.setForeground(new java.awt.Color(248, 247, 244));
        btnSortMostPrice.setText("Sort by Most Price");
        btnSortMostPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortMostPriceActionPerformed(evt);
            }
        });

        btnSortCategoryDesc.setBackground(new java.awt.Color(133, 169, 143));
        btnSortCategoryDesc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSortCategoryDesc.setForeground(new java.awt.Color(248, 247, 244));
        btnSortCategoryDesc.setText("Sort Category Desc");
        btnSortCategoryDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortCategoryDescActionPerformed(evt);
            }
        });

        btnSortLeastPrice.setBackground(new java.awt.Color(133, 169, 143));
        btnSortLeastPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSortLeastPrice.setForeground(new java.awt.Color(248, 247, 244));
        btnSortLeastPrice.setText("Sort by Least Price");
        btnSortLeastPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortLeastPriceActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(248, 247, 244));

        jButton1.setBackground(new java.awt.Color(133, 169, 143));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(248, 247, 244));
        jButton1.setText("Search");

        javax.swing.GroupLayout pnlAllProductsLayout = new javax.swing.GroupLayout(pnlAllProducts);
        pnlAllProducts.setLayout(pnlAllProductsLayout);
        pnlAllProductsLayout.setHorizontalGroup(
            pnlAllProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllProductsLayout.createSequentialGroup()
                .addGroup(pnlAllProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAllProductsLayout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(lblOurProducts))
                    .addGroup(pnlAllProductsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnlAllProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAllProductsLayout.createSequentialGroup()
                                .addComponent(btnSortId)
                                .addGap(30, 30, 30)
                                .addComponent(btnSortCategory)
                                .addGap(18, 18, 18)
                                .addComponent(btnSortCategoryDesc)
                                .addGap(18, 18, 18)
                                .addComponent(btnSortMostPrice)
                                .addGap(30, 30, 30)
                                .addComponent(btnSortLeastPrice))))
                    .addGroup(pnlAllProductsLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlAllProductsLayout.setVerticalGroup(
            pnlAllProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllProductsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblOurProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlAllProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(pnlAllProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortId)
                    .addComponent(btnSortCategory)
                    .addComponent(btnSortCategoryDesc)
                    .addComponent(btnSortMostPrice)
                    .addComponent(btnSortLeastPrice))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        tabbedPane.addTab("All Products", pnlAllProducts);

        pnlAddProducts.setBackground(new java.awt.Color(248, 247, 244));

        pnlRegistrationForm.setBackground(new java.awt.Color(82, 91, 68));
        pnlRegistrationForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductRegister.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblProductRegister.setForeground(new java.awt.Color(248, 247, 244));
        lblProductRegister.setText("Product Registration");
        pnlRegistrationForm.add(lblProductRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 38));

        txtId.setBackground(new java.awt.Color(248, 247, 244));
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnlRegistrationForm.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 104, 60));

        txtProduct.setBackground(new java.awt.Color(248, 247, 244));
        txtProduct.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnlRegistrationForm.add(txtProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 202, 60));

        txtPrice.setBackground(new java.awt.Color(248, 247, 244));
        txtPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnlRegistrationForm.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 152, 60));

        txtDescription.setBackground(new java.awt.Color(248, 247, 244));
        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        scrollPane.setViewportView(txtDescription);

        pnlRegistrationForm.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 260, -1));

        boxYarn.setBackground(new java.awt.Color(248, 247, 244));
        boxYarn.setEditable(true);
        boxYarn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton", "Wool", "Acrylic", "Chunky", "Cashmere" }));
        boxYarn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Yarn Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnlRegistrationForm.add(boxYarn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 120, 60));

        checkRepairable.setBackground(new java.awt.Color(248, 247, 244));
        checkRepairable.setForeground(new java.awt.Color(153, 153, 153));
        checkRepairable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        checkRepairable.setLabel("Repairable");
        pnlRegistrationForm.add(checkRepairable, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 160, 100, 60));

        boxCategory.setBackground(new java.awt.Color(248, 247, 244));
        boxCategory.setEditable(true);
        boxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sweater", "Scarf", "Cardigan" }));
        boxCategory.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnlRegistrationForm.add(boxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 120, 60));

        spinStock.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnlRegistrationForm.add(spinStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 100, 60));

        btnAddProduct.setBackground(new java.awt.Color(133, 169, 143));
        btnAddProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        pnlRegistrationForm.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 124, 41));

        btnUpdateProduct.setBackground(new java.awt.Color(133, 169, 143));
        btnUpdateProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateProduct.setText("Update Product");
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });
        pnlRegistrationForm.add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, 41));

        btnDeleteProduct.setBackground(new java.awt.Color(133, 169, 143));
        btnDeleteProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteProduct.setText("Delete Product");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });
        pnlRegistrationForm.add(btnDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, 41));

        lblIdError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblIdError.setForeground(new java.awt.Color(255, 153, 51));
        lblIdError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlRegistrationForm.add(lblIdError, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, 11));

        lblProdError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblProdError.setForeground(new java.awt.Color(255, 153, 51));
        lblProdError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlRegistrationForm.add(lblProdError, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 220, 10));

        lblPriceError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblPriceError.setForeground(new java.awt.Color(255, 153, 51));
        lblPriceError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlRegistrationForm.add(lblPriceError, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 183, 10));

        lblStockError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblStockError.setForeground(new java.awt.Color(255, 153, 51));
        lblStockError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlRegistrationForm.add(lblStockError, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 163, 10));

        lblCategoryError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblCategoryError.setForeground(new java.awt.Color(255, 153, 51));
        lblCategoryError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlRegistrationForm.add(lblCategoryError, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 155, 10));

        lblYarnError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblYarnError.setForeground(new java.awt.Color(255, 153, 51));
        lblYarnError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlRegistrationForm.add(lblYarnError, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 155, 10));

        javax.swing.GroupLayout pnlAddProductsLayout = new javax.swing.GroupLayout(pnlAddProducts);
        pnlAddProducts.setLayout(pnlAddProductsLayout);
        pnlAddProductsLayout.setHorizontalGroup(
            pnlAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddProductsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(pnlRegistrationForm, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlAddProductsLayout.setVerticalGroup(
            pnlAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddProductsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlRegistrationForm, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Add Products", pnlAddProducts);

        btnLogout.setBackground(new java.awt.Color(133, 169, 143));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Log-Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(32, 32, 32))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        lblTagline.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lblTagline.setForeground(new java.awt.Color(248, 247, 244));
        lblTagline.setText("Made With The Touch of Hand");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 650));
        setMinimumSize(new java.awt.Dimension(900, 650));
        setPreferredSize(new java.awt.Dimension(900, 650));

        pnlLoading.setBackground(new java.awt.Color(82, 91, 68));
        pnlLoading.setMaximumSize(new java.awt.Dimension(900, 600));
        pnlLoading.setMinimumSize(new java.awt.Dimension(900, 600));
        pnlLoading.setPreferredSize(new java.awt.Dimension(900, 600));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/theyarnest/resources/theYarnestLogo (1).png"))); // NOI18N

        lblLoading.setForeground(new java.awt.Color(242, 242, 242));
        lblLoading.setText("Loading...");

        lblYarNest.setForeground(new java.awt.Color(242, 242, 242));
        lblYarNest.setText("The YarNest");

        lblCopyright.setForeground(new java.awt.Color(242, 242, 242));
        lblCopyright.setText("©Copyright The YarNest 2024");

        javax.swing.GroupLayout pnlLoadingLayout = new javax.swing.GroupLayout(pnlLoading);
        pnlLoading.setLayout(pnlLoadingLayout);
        pnlLoadingLayout.setHorizontalGroup(
            pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingLayout.createSequentialGroup()
                .addComponent(lblYarNest, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCopyright)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingLayout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingLayout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(298, 298, 298))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(408, 408, 408))
        );
        pnlLoadingLayout.setVerticalGroup(
            pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingLayout.createSequentialGroup()
                .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYarNest)
                    .addComponent(lblCopyright))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //method to add panels and layout to the frame
    private void layoutInitialize() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(pnlLoading, "LoadScreen");
        getContentPane().add(pnlLogin, "LoginScreen");
        getContentPane().add(pnlMain, "MainScreen");

        // Start with the loading screen
        cardLayout.show(getContentPane(), "LoadScreen");
    }

    //method to initialize data
    private void dataInitialize() {
        productList = new LinkedList<>();
        sortedList = new LinkedList<>();

        addProduct(new CrochetModel(1, "Cozy Sweater", "Sweater", "Wool", true,
                "Wool by Sam", (float) 95.00, 3, "2024-12-13"));
        addProduct(new CrochetModel(2, "Granny Cardigan", "Cardigan", "Acrylic", false,
                "Dang", (float) 105.00, 2, "2024-12-20"));
        addProduct(new CrochetModel(3, "Wrap around Scarf", "Scarf", "Cotton", true,
                "Hand made by Sammy", (float) 50.00, 6, "2024-12-21"));
        addProduct(new CrochetModel(6, "Buttonless Cardigan", "Cardigan", "Wool", true,
                "Dang", (float) 125.00, 7, "2024-12-29"));
        addProduct(new CrochetModel(8, "Winter Scarf", "Scarf", "Cashmere", false,
                "Dang", (float) 55.00, 6, "2024-12-30"));
        addProduct(new CrochetModel(5, "Fluff Sweater", "Sweater", "Chunky", true,
                "Dang", (float) 150.00, 9, "2024-12-20"));

    }

    /* Method to simulate loading progress for the progress bar
    */
    private void forProgressBar() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i);
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                progressBar.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute();
    }

    /* Method to add the products data into the table
    * @params productList list of products 
    *stores the list of products to productList
    */
    private void addProduct(CrochetModel product) {
        productList.add(product);
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
        model.addRow(new Object[]{
            product.getProdId(), product.getProdName(), product.getCategory(), 
            product.getYarnType(), product.isRepairable(), product.getDescription(), 
            product.getPrice(), product.getStock(), product.getDateAdded(),});
    }

    /* Method to switch screens, loading the screenName
    * uses cardLayout to render the page contents
    * screenName: the name for the screen to load
    */
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get the input from log-in page
        String userName = txtUserName.getText();
        String password = new String(txtPassword.getPassword());

        // Check if fields are empty
        if (userName.isEmpty() || password.isEmpty()) {
            lblError.setText("Please enter your username and password!");
        } // Check username and password
        else if (!userName.equals("admin") || !password.equals("admin")) {
            lblError.setText("Username and password don't match!!!");
        } // Proceed to load the main screen after datas are validated
        else {
            lblError.setText(""); // Clear previous error messages
            loadScreen("MainScreen"); // Load main screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        txtPassword.setText("");
        txtUserName.setText("");
        loadScreen("LoginScreen"); // Load the main screen
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        // Get Product Id from the text field
        String prodId = txtId.getText();

        // Check if Product Id is empty
        if (prodId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Product Id is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
        boolean found = false;

        // Loop through the table to find the product
        for (int i = 0; i < model.getRowCount(); i++) {
            // Check if the value for product id is not null
            Object id = model.getValueAt(i, 0);
            if (id != null && id.toString().equals(prodId)) {
                // Update the stock, price
                String newPrice = txtPrice.getText();
                int newStock = (int) spinStock.getValue();

                if (!ValidationUtil.isValidStock(newStock)) {
                    lblStockError.setText("Stock must be more than -1 & less than 100.");
                    return;
                } else {
                    lblStockError.setText(""); // Clear previous error messages
                }

                if (!ValidationUtil.isValidPrice(newPrice)) {
                    lblPriceError.setText("Enter positive decimals and digits only.");
                    return;
                } else {
                    lblPriceError.setText(""); // Clear previous error messages
                }
                // Update stock and price values
                model.setValueAt(newPrice, i, 6);
                model.setValueAt(newStock, i, 7);

                found = true;
                break;
            }
        }

        if (found) {
            JOptionPane.showMessageDialog(this, "Product Updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
            tblProducts.setVisible(true);
            tblProducts.repaint();
            tblProducts.revalidate();
        } else {
            JOptionPane.showMessageDialog(this, "Product Id not found!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // To add the products from the form into the linkedlist
        String productId = txtId.getText();
        String productName = txtProduct.getText();
        String category = (String) boxCategory.getSelectedItem();
        String yarnType = (String) boxYarn.getSelectedItem();
        boolean repairable = checkRepairable.isSelected();
        String description = txtDescription.getText();
        String price = txtPrice.getText();
        int stock = (int) spinStock.getValue();

        SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
        String currentDate = formatDate.format(new Date());

        // Checking for id before adding the products
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            String idExists = model.getValueAt(i, 0).toString();
            if (idExists.equals(productId)) {
                lblIdError.setText("Id already exists");
                return;
            } else {
                lblIdError.setText(""); // Clear previous error messages
            }
        }

        if (ValidationUtil.isNullOrEmpty(productId)) {
            lblIdError.setText("Field is Empty");
            return;
        }
        else if (!ValidationUtil.isValidId(productId)) {
            lblIdError.setText("Enter digits only.");
            return;
        } else {
            lblIdError.setText(""); // Clear previous error messages
        }

        if (ValidationUtil.isNullOrEmpty(productName)) {
            lblProdError.setText("Field is Empty");
            return;
        }
        else if (!ValidationUtil.isValidProdName(productName)) {
            lblProdError.setText("Enter letters and spaces.");
            return;
        }else {
            lblProdError.setText(""); // Clear previous error messages
        }

        if (!ValidationUtil.isValidCategory(category)) {
            lblCategoryError.setText("Select from below.");
            return;
        }
        else {
            lblCategoryError.setText(""); // Clear previous error messages
        }

        if (!ValidationUtil.isValidYarnType(yarnType)) {
            lblYarnError.setText("Select from below.");
            return;
        } else {
            lblYarnError.setText(""); // Clear previous error messages
        }

        if (!ValidationUtil.isValidStock(stock)) {
            lblStockError.setText("Stock must be more than -1 & less than 100.");
            return;
        } else {
            lblStockError.setText(""); // Clear previous error messages
        }

        if (ValidationUtil.isNullOrEmpty(price)) {
            lblPriceError.setText("Field is empty");
            return;
        }else if (!ValidationUtil.isValidPrice(price)) {
            lblPriceError.setText("Enter positive decimals and digits only.");
            return;
        } else {
            lblPriceError.setText(""); // Clear previous error messages
        }

        CrochetModel product = new CrochetModel(Integer.parseInt(productId), 
                productName, category, yarnType, repairable, description, 
                Float.parseFloat(price), stock, currentDate);

        productList.add(product);
        addToTable(productList);

        JOptionPane.showMessageDialog(this, "Product Registered!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // Get Product Id from the text field
        String prodId = txtId.getText();

        // Check if Product Id is empty
        if (prodId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Product Id is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirm the delete process
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete Product : " + prodId + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

        // Do nothing if the user selects "No"
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
        boolean found = false;

        // Loop through table to find the matching Product Id
        for (int i = 0; i < model.getRowCount(); i++) {
            // Check if the value if the id is not null
            Object id = model.getValueAt(i, 0);
            if (id != null && id.toString().equals(prodId)) {
                // Remove the row with the product if id matches
                model.removeRow(i);
                found = true;
                break;
            }
        }
        if (found) {
            JOptionPane.showMessageDialog(this, "Product deleted!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Product ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteProductActionPerformed

    /* Method to manipulate products data in the table for sorting
    * @params productList list of products 
    * populates the table with the product data through table model
    */
    private void addToTable(List<CrochetModel> productList) {
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();

        // Clear existing rows if needed
        model.setRowCount(0);

        // Populate the table with product data
        productList.forEach(product -> model.addRow(new Object[]{
            product.getProdId(), product.getProdName(), product.getCategory(), 
            product.getYarnType(), product.isRepairable(), product.getDescription(), 
            product.getPrice(), product.getStock(), product.getDateAdded()}));
    }
    
    private void btnSortIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortIdActionPerformed
        sortedList = selectionSort.sortById(productList, false);
        
        addToTable(sortedList);
    }//GEN-LAST:event_btnSortIdActionPerformed

    private void btnSortCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortCategoryActionPerformed
        sortedList = insertionSort.sortByCategory(productList, false);
        
        addToTable(sortedList);        
    }//GEN-LAST:event_btnSortCategoryActionPerformed

    private void btnSortMostPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortMostPriceActionPerformed
        sortedList = mergeSort.sortByPrice(productList, true);
        
        addToTable(sortedList);
    }//GEN-LAST:event_btnSortMostPriceActionPerformed

    private void btnSortCategoryDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortCategoryDescActionPerformed
        sortedList = insertionSort.sortByCategory(productList, true);
        
        addToTable(sortedList);
    }//GEN-LAST:event_btnSortCategoryDescActionPerformed

    private void btnSortLeastPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortLeastPriceActionPerformed
        sortedList = mergeSort.sortByPrice(productList, false);
        
        addToTable(sortedList);
    }//GEN-LAST:event_btnSortLeastPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheYarnestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheYarnestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheYarnestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheYarnestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheYarnestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCategory;
    private javax.swing.JComboBox<String> boxYarn;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSortCategory;
    private javax.swing.JButton btnSortCategoryDesc;
    private javax.swing.JButton btnSortId;
    private javax.swing.JButton btnSortLeastPrice;
    private javax.swing.JButton btnSortMostPrice;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JCheckBox checkRepairable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCategoryError;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblCozyGreenSweater;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblForgetPassword;
    private javax.swing.JLabel lblGrannySquareCardigan;
    private javax.swing.JLabel lblHalfSweater;
    private javax.swing.JLabel lblIdError;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLoginIcon;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblOurProducts;
    private javax.swing.JLabel lblPriceError;
    private javax.swing.JLabel lblProdError;
    private javax.swing.JLabel lblProductRegister;
    private javax.swing.JLabel lblSignin;
    private javax.swing.JLabel lblStockError;
    private javax.swing.JLabel lblTagline;
    private javax.swing.JLabel lblYarNest;
    private javax.swing.JLabel lblYarnError;
    private javax.swing.JLabel lblgrannyCardigan;
    private javax.swing.JPanel pnlAddProducts;
    private javax.swing.JPanel pnlAdminControls;
    private javax.swing.JPanel pnlAllProducts;
    private javax.swing.JScrollPane pnlBrandMessage;
    private javax.swing.JPanel pnlForBrand;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlLoading;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRegistrationForm;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JSpinner spinStock;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
